# Configuration for Travis-CI

language: java

sudo: required

env:
  global:
    - MAVEN_VERSION: "3.8.1"
    - MAVEN_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx1g" #-Dorg.slf4j.simpleLogger.defaultLogLevel=warn 
    - MAVEN_COMPILATION_OPTS: "\"-e\""
    - secure: "akKEf27hEycPBpOjfQQ6O3Gt92IlgQCl+fRnmN2kZxBE7Gnm/BqDHQbM/IbixzfWWthvaIgI85BTljNRH2qNq5W/GSPixUd9bfqKI9WL8b1uvv00OxOXsPOcqbEjxBVP0zivxpPDWNX1Fefu7W4Lb/Yaa2ju5uCMBxTl1r2ug5U="
    - secure: "RE+Lasgu9mUS78kjPRMrx35UpO/AQ1kuUUSd0lrBXwajZjpHSTRwVx0cudjSet2hEjAwRyerbKZ4zLxm+HxeMQBzjws4nhHozar/2XeY6mgvHYQ6G3kRFhNMr5WZn1CAu5Gu2OxqE6az/J6mQUDnMF1/XNL/bPhKEZsUI8o24eA="

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - openjfx
          - xvfb
      jdk: openjdk11
      env:
      - OPENJFX_LIB_PATH: "/usr/share/java/openjfx/jre/lib/ext/jfxrt.jar"
      - M2_HOME: "$HOME/.binaries/apache-maven-${MAVEN_VERSION}"
      - PATH: "$M2_HOME/bin:$PATH"
      services:
      - xvfb
      before_install:
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS\"" > $HOME/.mavenrc
      - ./build-tools/src/main/resources/bash/travis-download-maven.sh "$MAVEN_VERSION"
    - os: osx
      osx_image: xcode10.1 # see https://docs.travis-ci.com/user/osx-ci-environment/
      env:
      - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
      before_install:
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS\"" > $HOME/.mavenrc


install: true

script: mvn -B $MAVEN_COMPILATION_OPTS install

cache:
  directories:
  - $HOME/.m2
  - $HOME/.binaries

#after_success:
#  - "[[ ${TRAVIS_OS_NAME} == 'linux' ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && [[ ${TRAVIS_BRANCH} == 'master' ]] && mvn -B deploy -DskipTests -Dcheckstyle.skip=true --settings build-tools/src/main/resources/maven/deploy-settings.xml"

