= How to contribute
:toc: right
:toc-placement!:
:hide-uri-scheme:

Any contribution to the AFC library is welcome.

== 1. Installing the Development Environment

For setting up the development environment, you should follow the steps:

* Download and install "Eclipse for Java Developers".
* Download the link:./build-tools/src/main/resources/eclipse/contributors.p2f[contributors.p2f] file that specifies the Eclipse plugins for the development environment.
* Install the Eclipse plugins by selecting in Eclipse: `File > Import > Install > Install software items from file.`
* Download the link:./build-tools/src/main/resources/eclipse/contributors.epf[contributors.epf] file that contains the Eclipse general preferences related to the AFC project.
* Import the general preferences: `File > Import > General > Preferences`

== 2. Obtaining the AFC Source Code

For obtaining the code of the AFC library, you must clone it from the Git:
```bash
git clone https://github.com/gallandarakhneorg/afc
```

CAUTION: Due to an issue in the Eclipse Checkstyle plugin, it is mandatory to install the `build-tools` module in the your `.m2` repository prior to the first launch of the Eclipse IDE: `mvn clean install -Dcheckstyle.skip=true`

== 3. Compiling the AFC Source Code

Maven is the standard tool for compiling the AFC library. It is recommended to launch the Maven compilation process on the command at least before submitting a pull request. The command line is:
```bash
mvn clean install
```

== 4. Sending the Contribution

For sending your contribution to the AFC master repositoty, you must request a pull (PR) to the link:https://github.com/gallandarakhneorg/afc/[GitHub repository].

For being merged, your must ensure the following points:

* Your PR must be compilable with Maven.
* Your PR must pass the compilation process successfully, including the code compilation, unit tests, and code style checking. This process is supported by Travis-CI for linux and OSX platforms, and AppVeyor for Windows platforms.
* You must sign the link:./CLA.md[Contributor License Agreement] on GitHub. It is supported by link:https://cla-assistant.io/gallandarakhneorg/afc[cla-assistant].
* Your PR should be reviewed by one or more of the main contributors for ensure it is following the development rules and philosophy related to AFC.

The page of your PR on Github is displaying the status of your PR.
If one point is failing, please follows the steps:

* Go on the Travis-CI or AppVeyor console for obtaining the cause of the failure.
* Fix the code of your PR on your local copy.
* Commit on your local repository, compile, and test until you have fixed the issue.
* Push the changes on the same PR, i.e. the same Git repository as the one used for the PR. *Do not create a new PR for the fix.*
* The GitHub platform will relaunch the CI process automatically.


