/*
 * 
 * $Id$
 * 
 * Copyright (c) 2006-09, Multiagent Team - Systems and Transportation Laboratory (SeT)
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of the Systems and Transportation Laboratory ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with the SeT.
 * 
 * http://www.multiagent.fr/
 */
package org.arakhne.afc.jasim.environment.model.actions;

import java.util.Collection;

import fr.utbm.set.collection.SizedIterable;

import org.arakhne.afc.jasim.environment.interfaces.internalevents.EnvironmentalAction;

/**
 * The class in charge of dispatching action that modify the environment states and structures.
 * 
 * @param <EA> is the type of supported actions
 * @author $Author: sgalland$
 * @author $Author: ngaud$
 * @version $Name$ $Revision$ $Date$
 * @mavengroupid $GroupId$
 * @mavenartifactid $ArtifactId$
 */
public interface EnvironmentalActionCollector<EA extends EnvironmentalAction> {
	
	/**
	 * @param action will be dispatch.
	 */
	public void addAction(EA action);

	/**
	 * @param actions is the list of actions to dispatch.
	 */
	public void addActions(Collection<? extends EA> actions);

	/**
	 * Returns the set of collected actions generated by the 
	 * environment through its internal components.
	 * <p>
	 * This function also clear the internal data structures.
	 * 
	 * @return the set of collected actions generated by the environment.
	 */
	public SizedIterable<EA> consumeActions() ;

}
