/*
 * 
 * $Id$
 * 
 * Copyright (c) 2006-09, Multiagent Team - Systems and Transportation Laboratory (SeT)
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of the Systems and Transportation Laboratory ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with the SeT.
 * 
 * http://www.multiagent.fr/
 */
package org.arakhne.afc.jasim.environment.model.influences;

import fr.utbm.set.collection.SizedIterable;

import org.arakhne.afc.jasim.environment.interfaces.body.influences.Influencable;
import org.arakhne.afc.jasim.environment.interfaces.body.influences.Influence;
import org.arakhne.afc.jasim.environment.interfaces.body.influences.Influencer;

/**
 * This interface permits to collect the influences from the bodies and
 * from external sources.
 * 
 * @author $Author: sgalland$
 * @author $Author: ngaud$
 * @version $Name$ $Revision$ $Date$
 * @mavengroupid $GroupId$
 * @mavenartifactid $ArtifactId$
 */
public interface InfluenceCollector {
	
	/**
	 * Add a new influence.
	 * If the influences has a <code>null</code> influenced object and if
	 * the <var>influencer</var> parameter is not <code>null</code>,
	 * this function will force the influences to be applied to the
	 * given influencer.
	 * 
	 * @param defaultInfluencer is the default influencer for all the given influences.
	 * @param defaultInfluencedObject is the object that should be influenced by default, or <code>null</code> 
	 * @param influence - the influence to add
	 */
	public void registerInfluence(Influencer defaultInfluencer, Influencable defaultInfluencedObject, Influence... influence) ;
  
	/**
	 * Returns the set of collected standard influences generated by the agents
	 * and by the environment through its internal dynamics.
	 * <p>
	 * A standard influence is an influence which do not change the population
	 * length.
	 * <p>
	 * This function also clear the internal data structures.
	 * 
	 * @return the set of collected influences generated by the agents
	 * and by the environment through its internal dynamics
	 * @see #consumePopulationInfluences()
	 */
	public SizedIterable<? extends Influence> consumeStandardInfluences() ;
  
	/**
	 * Returns the set of collected population influences generated by the agents
	 * and by the environment through its internal dynamics.
	 * <p>
	 * A population influence is an influence which tends to change the
	 * population length (killing, borning...).
	 * <p>
	 * This function also clear the internal data structures.
	 * 
	 * @return the set of collected influences generated by the agents
	 * and by the environment through its internal dynamics
	 * @see #consumeStandardInfluences()
	 */
	public SizedIterable<? extends Influence> consumePopulationInfluences() ;

}
